sonar.projectKey=my-idlers
sonar.projectName=my-idlers

sonar.sources=app,config,database,routes,resources/js
sonar.tests=tests
sonar.exclusions=**/vendor/**,**/node_modules/**,public/**,storage/**,bootstrap/cache/**,database/seeders/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
